### ISSUE TITLE
Figure out Class Hierarchy

### ISSUE THREAD

**Issue by jjbott** [jjbott/RocketLeagueReplayParser#10]
The class hierarchy information has ambiguous data in it, which I'm currently manually fixing. There are several cases where classes do not have unique ids, making it difficult to match up the correct child classes. 

Seems like this has always been a problem, but it hadn't caused parsing errors until recently. Most common parsing errors I've had involve CarComponent classes that think their parent is TeamInfo, which is incorrect.

It's possible that the data is being read incorrectly, but I think that's unlikely since it's so simple. Either the data is being interpreted incorrectly, or that information is not even used by Rocket League.

Figure it out!

**Comment by tfausak** [comment]
Sounds a lot like https://github.com/tfausak/octane/issues/37. I haven't figured it out yet.

**Comment by jjbott** [comment]
Ha, yep! I've just been manually fixing the parent/child relationship of a few classes. That works just fine, but smells wrong.

**Comment by tfausak** [comment]
For what it's worth I gave up on trying to figure this out from the data in the replays. I have a hard-coded map from classes to their parent classes. I do make sure that the "parent cache ID" in the replay is sensible, but I use my hard-coded map to do the real work. I was unable to make sense of the replay data without doing this.

**Comment by jjbott** [comment]
Yeah, I havent really been trying to figure it out either. The hardcoded mappings work fine. Still seems fishy that that data doesn't make a bit of sense. Like, what purpose could it possibly have if we have to hand map things anyways? Oh well. Maybe I'll just close this and forget we ever talked about it. Shh. :)
