### ISSUE TITLE
How fast is this?

### ISSUE THREAD

**Issue by tfausak** [jjbott/RocketLeagueReplayParser#11]
I would like to know how quickly this parser turns a replay into JSON. Unfortunately I have never set up a C# project before and this repository doesn't have any instructions. 

Out of curiosity, can you tell me how long it takes to parse this replay? [B82DDB624C393A4A425E68AB40DC2450.replay.zip](https://github.com/jjbott/RocketLeagueReplayParser/files/588172/B82DDB624C393A4A425E68AB40DC2450.replay.zip)

Thanks!

**Comment by jjbott** [comment]
That's the broken one that even crashes Rocket League. My parser crashes within a second, when it gets to the bad frame at the end. I'm too lazy to figure out exactly how fast it crashes. :) I could probably fudge something so it'd work, and even fix up the replay so it doesn't crash Rocket League anymore. But, eh... No one really uses this parser, except maybe to copy it.

**Comment by tfausak** [comment]
Oops, sorry! I didn't mean to set you up for failure there. How about [this replay](https://github.com/tfausak/rattletrap/blob/master/test/replays/DCB3A6B94A9DBE46FDE5EAA9B012F6C8.replay)?

**Comment by jjbott** [comment]
That one converts to JSON in about 11.8-12.9 seconds, depending on how fast my potato computer decides to be. :) If I remember right, that's going to be about 10% parsing and 90% mashing it into whatever version of JSON I though was a good idea 6 months ago.

**Comment by tfausak** [comment]
Great, thank you! Data mashing is always the expensive part.

**Comment by jjbott** [comment]
No problem! I should release an updated console version one of these months...
