### ISSUE TITLE
Is there a way to get just header info?

### ISSUE THREAD

**Issue by rmogstad** [jjbott/RocketLeagueReplayParser#14]
I am trying to write something similar to https://github.com/TcT2k/RLReplayManager/releases (in C#) since that one has some issues with newer replays.  

Is there any way to get just header info (similar to https://github.com/rocket-league-replays/rocket-league-replays/blob/develop/rocket_league/apps/replays/parser.py#L91) using this library?  (presumably this would be faster than parsing the entire replay)

It has been a few weeks since I looked at your library, but I was unable to quickly grab the info I was looking for (e.g. Name, players, score, etc.).

If this doesn't exist, I am happy to work on it and submit a PR.

**Comment by jjbott** [comment]
Not currently, no. It'll only parse the whole mess for you. It'd be pretty easy to add something though. The Deserialize method in the Replay class would just need to be tweaked so it'd stop after the Property do/while loop. I can whip something up over the weekend if you don't give it a shot first. :)

Also the list of Property classes is pretty raw. Some helpers to more easily extract data from there would be pretty nice. It's not exactly tough, but, for example, a quick bit of code to get player names might look something like `replay.Properties.Where(p => p.Name == "PlayerStats").Single().ArrayValue.Select(p => p.Where(p2 => p2.Name == "Name").Single().StringValue);`. Yeah pretty gross. Hmmm.

**Comment by rmogstad** [comment]
Cool, I will try to get to it tonight or over the weekend too.  I wonder if just setting properties on Replay when you parse would be OK, rather than re-searching the whole structure.  Alternatively a separate Metadata class could be constructed after parsing header info, and assigned to the replay?

**Comment by jjbott** [comment]
I didn't get to this at all, but my initial thought is that all `List<Property>`s could at least be changed to `Dictionary<string, Property>`s, indexed by name. Some sort of "PropertyCollection" class might be better so the serialization logic for a collection can be centralized, but the Dictionary would get things started. Beyond that, a better typed `Property` class would be nice. I might try converting it to a `Property<T>` to see how awful that looks.

**Comment by rmogstad** [comment]
I came up with a solution (sort of), but did so by pulling out some of your code.  I will re-integrate into your code and see what you think sometime in the next couple of days.  

It's very quick, loads 150 replays in <1s

**Comment by tfausak** [comment]
@rmogstad: Yeah, parsing just header information is crazy fast. All the fields are known lengths and you don't need to do any bit twiddling. 

@jjbott: I put the properties in a type I called [`Dictionary`](https://www.stackage.org/haddock/nightly-2016-12-12/rattletrap-2.0.0/Rattletrap-Primitive-Dictionary.html), which is just a map from strings to properties. I created my own type to remember the order of the keys. 

I call the properties themselves [`Property`](https://www.stackage.org/haddock/nightly-2016-12-12/rattletrap-2.0.0/Rattletrap-Property.html), but the interesting part is the inner [`PropertyValue`](https://www.stackage.org/haddock/nightly-2016-12-12/rattletrap-2.0.0/Rattletrap-PropertyValue.html#t:PropertyValue). I'm not sure how to make a data structure like that in C#, but I assume it's possible.

**Comment by jjbott** [comment]
I added a PR that exposes a "DeserializeHeader" method, and also tries to make properties easier to use. That linq mess above would now be `replay.Properties["PlayerStats"].Select(p => p["Name");` which is a little better. It's a little hacky (exposing a value that can be one of many types in a simple way is weird) but using the data is significantly easier. Might be cleaner with `dynamic`, maybe I'll rewrite it again someday.

Made a PR in case people want to comment on the sketchy code before I merge it. :)

**Comment by rmogstad** [comment]
I don't have any comments.  I will update to use it at some point instead of the copy/paste/hack implementation that I went with (borrowed from this project, if you aren't cool with that I am happy to delete the repo until I update to use your code directly).  I have uploaded my current version , with basic functionality complete: https://github.com/rmogstad/RLReplayManager

**Comment by jjbott** [comment]
Oh gosh I got distracted this week and forgot about this. I've merged it!  I'll have a new Nuget package pushed soon
