### ISSUE TITLE
Fix replay creation

### ISSUE THREAD

**Issue by jjbott** [jjbott/RocketLeagueReplayParser#16]
The state of the replay serialization code hasn't kept up with the addition of new classes/properties over the last several months. Get it working on all new replays again.

If anyone would actually like to use this to create replays let me know. Otherwise I'm in no hurry to fix this.

**Comment by tfausak** [comment]
Just in case someone lands here looking to generate Rocket League replays, my tool [Rattletrap](https://github.com/tfausak/rattletrap) can do that! 😄
