### ISSUE TITLE
Missing "delta" field.

### ISSUE THREAD

**Issue by enzanki-ars** [jjbott/RocketLeagueReplayParser#18]
In other parsers (octane and rattletrap specifically), there is a delta field present in the resulting JSON output.  WIthout this field, the resulting output contains an additional 5 seconds added in after every goal, most likely where the goal replay was.  Sadly, this causes issue when aligning the video with the recorded video of the replay.  Is it possible to add that field into the JSON output?

**Comment by enzanki-ars** [comment]
To elaborate, it seem that the delta field is right after the time field.  See https://github.com/tfausak/rattletrap/blob/e88f4be14de8cad31ecf01f0b97309188b557394/library/Rattletrap/Frame.hs#L14, https://github.com/tfausak/rattletrap/blob/e88f4be14de8cad31ecf01f0b97309188b557394/library/Rattletrap/Frame.hs#L55, and https://github.com/tfausak/rattletrap/blob/e88f4be14de8cad31ecf01f0b97309188b557394/library/Rattletrap/Frame.hs#L66 for examples.

**Comment by enzanki-ars** [comment]
It seems this may be easier to add in than I thought.  I will create a pull request for this addition.

**Comment by jjbott** [comment]
Thanks! Yeah, ages ago I purposely left it out of the "pretty" JSON because at the time it **seemed** to always be (<frame time> - <previous frame time>), basically making it redundant.
