### ISSUE TITLE
[Feature Request] Output replay time along side replay date if possible.

### ISSUE THREAD

**Issue by enzanki-ars** [jjbott/RocketLeagueReplayParser#28]
I was looking at the `Properties` in the replays and noticed that there is a `Date` field, but I do not see a `Time` field.  

Is there a `Time` field in the replays?  If so, would it be possible to output that data?

**Comment by enzanki-ars** [comment]
Oh.  I'm an idiot... It was right there all along....

`'Date': '2017-12-02 18-04-28'`

**Comment by jjbott** [comment]
Heh, no worries! Before I went to bed I was thinking "I swear its in there, how did I mess that up?" :)
