### ISSUE TITLE
New replays seem to run into an unknown property error.

### ISSUE THREAD

**Issue by Hundisilm** [jjbott/RocketLeagueReplayParser#32]
System.NotSupportedException
  HResult=0x80131515
  Message=Unknown property TAGame.GameEvent_Soccar_TA:bClubMatch.

**Comment by jjbott** [comment]
Aw man! I'll tackle this later today. If it's just this property it should be easy. 🤞

**Comment by jjbott** [comment]
I've pushed a new version, let me know if it works for you. Unfortunately I haven't been able to generate a replay with that property, so I pushed my best guess. 😞 If you have a link to a replay with that property, that'd be great

**Comment by jjbott** [comment]
Pff, thats cheating. But yeah that's what I did, phew. Closing!
