### ISSUE TITLE
Unhandled platform id 7

### ISSUE THREAD

**Issue by cubeee** [jjbott/RocketLeagueReplayParser#34]
Hey again. The attached replay contains a reserved player on unhandled platform with id 7 that seems to be called PsyNet according to [this project](https://github.com/TaylorSasser/RLForge/blob/master/RLForge/RLForge/RL/SDK/RL_Engine_structs.hpp#L254) and the size is 32 bytes like Switch.

[D52EB3FA47646B38BD989FADF837F175.zip](https://github.com/jjbott/RocketLeagueReplayParser/files/2659903/D52EB3FA47646B38BD989FADF837F175.zip)

**Comment by jjbott** [comment]
Thanks!
