### ISSUE TITLE
Update Package to 2.0.6 with new decals

### ISSUE THREAD

**Issue by rurriik** [jjbott/RocketLeagueReplayParser#36]
Hey, Can you update the nuget package version please ? 

It doesn't work to read replay with new decals ! (as long as i see, you did some modifications to implement this feature, but not upgade the package.)

**Comment by jjbott** [comment]
Yep, I just pushed it out! I was sort of waiting because I've heard there are more breaking changes that I haven't handled. But I haven't found any replays that break anything, so good enough I guess. :)
