### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by badubies** [jjbott/RocketLeagueReplayParser#40]
> Unhandled Exception: System.NotSupportedException: Unknown property TAGame.Car_TA:ReplicatedDemolish_CustomFX.

**Comment by jjbott** [comment]
>  case "TAGame.Car_TA:ReplicatedDemolish_CustomFX":

**Comment by jjbott** [comment]
Based on nothing, my guess is you're using the outdated console app? I released a new version for good measure.
