### ISSUE TITLE
PlayerReplicationInfo:Ping seems to be off

### ISSUE THREAD

**Issue by nerdybeast** [jjbott/RocketLeagueReplayParser#43]
Version: 2.10.0

Hey @jjbott love this library you put together! I do have a question though, when looking at the json the parser creates, I can see my ping (in this specific example) averages around ~16ms throughout the file:
```
{
  "Time": 165.08438,
  "Delta": 0.0337704,
  "DeletedActorIds": [],
  "ActorUpdates": [
    {
      "Id": 6,
      "Engine.PlayerReplicationInfo:Ping": 16
    },
    //...
  ]
}
```
However, I'm a West player and this was on an East server where in game, I usually hover anywhere from 60-90ms ping on an East server. 

Just curious if I'm reading this data wrong or if I should even trust this number to begin with.

Github won't let me add the replay file in here so I can add it to Google Drive or something (where you'd have access to it) if you want.

Thanks in advance for the help!

**Comment by jjbott** [comment]
Hi! It's just giving you the raw data from the replay, but looks like if you multiply it by 4 you'll get your _actual_ ping. The relevant code in UnrealEngine appears to be `SetPing(FMath::Min(255, (int32)(ExactPing * 0.25f)));`

**Comment by nerdybeast** [comment]
Awesome, thanks for the quick response. Multiplying by 4 does look better when I look at the average ping for each user in the replay. 

Thanks again!
