### ISSUE TITLE
Deserialize Tests fails on Season and Private matches

### ISSUE THREAD

**Issue by pvormste** [jjbott/RocketLeagueReplayParser#5]
Hello,
I'm working on a replay webshare app and using your library for creating a compatible JSON. I'm loving it so far, thank you for your effort!

I figured out, that deserialization tests are failing on replays of season matches and private matches.

You can download example replays :)
https://drive.google.com/file/d/0ByCG-aO43H7lTU9SaEVBMDRlcEU/view?usp=sharing (private match)
https://drive.google.com/file/d/0ByCG-aO43H7lTkV3Vm00cTdTQ0U/view?usp=sharing (season match)

I don't think that these types are so important, but for the sake of completeness - why shouldn't they be fixed? :)

**Comment by jjbott** [comment]
Awesome thanks! Looks like I managed to fix it up. I'd love to see how you're using it!

Nice to be at a point where bug reports make sense, and not just "Yeah it still doesnt work at all"
