### ISSUE TITLE
Case insensitive switch statement discussion

### ISSUE THREAD

**Issue by nerdybeast** [jjbott/RocketLeagueReplayParser#52]
Hey @jjbott I noticed the comment in this section of code:
```
case "Engine.GameReplicationInfo:ServerName":
case "Engine.PlayerReplicationInfo:PlayerName":
case "TAGame.Team_TA:CustomTeamName":
case "Engine.PlayerReplicationInfo:RemoteUserData":
case "TAGame.GRI_TA:NewDedicatedServerIP":
case "ProjectX.GRI_X:MatchGUID":
case "ProjectX.GRI_X:MatchGuid": // Can remove as duplicate in case the comparison is ever made case insensitive
case "TAGame.PRI_TA:CurrentVoiceRoom":
case "ProjectX.GRI_X:ReplicatedServerRegion":
    asp.Data = br.ReadString();
    break;
```
Would you be open to a PR where I make these switch statements case insensitive?
That would look something like:
```
case string prop when prop.IsInListIgnoreCase(
        "Engine.GameReplicationInfo:ServerName",
        "Engine.PlayerReplicationInfo:PlayerName",
        "TAGame.Team_TA:CustomTeamName",
        "Engine.PlayerReplicationInfo:RemoteUserData",
        "TAGame.GRI_TA:NewDedicatedServerIP",
        "ProjectX.GRI_X:MatchGUID",
        "TAGame.PRI_TA:CurrentVoiceRoom",
        "ProjectX.GRI_X:ReplicatedServerRegion"
    ):
    asp.Data = br.ReadString();
    break;
```
or more verbose:
```
case string prop when prop.EqualsIgnoreCase("Engine.GameReplicationInfo:ServerName"):
case string prop when prop.EqualsIgnoreCase("Engine.PlayerReplicationInfo:PlayerName"):
//ect...
    asp.Data = br.ReadString();
    break;
```
_OR_ we could really go ham and abstract out all the property names into lists of like types (meaning properties that need to be serialized into a string, another list for properties that need to be serialized into booleans) then you would end up with a much smaller case statement like:
```
case string prop when StringProperties.Contains(prop):
    asp.Data = br.ReadString();
    break;
case string prop when BooleanProperties.Contains(prop):
    asp.Data = br.ReadBit();
    break;
```
In all these approaches we would make the string comparison case insensitive to prevent issues like with `MatchGUID`.
Anyway I'd be curious on your thoughts about all of this. It looks like the C# language version your project is using is 7.3 which does support these switch expressions so this would totally be doable if you want me to jump in on it.

**Comment by jjbott** [comment]
Sorry I'm slow, forgot about this.

But I don't know. I'm not sure I'm on board with making it case-insensitive. It'd help for 1 special case, and add a smidge of unnecessary work for everything else - and there is a _ton_ of everything else. Maybe it wouldn't matter one bit, but think the 1 extra line wins. `¯\_(ツ)_/¯`

Abstracting out the lists in a better way could be nice. I wouldn't worry too much about it though. This thing has basically been in maintenance mode for years :)

**Comment by nerdybeast** [comment]
No worries at all, I was just digging through the library to try and understand some of this data better and came across this. I know this project is basically in maintenance mode but I'd love to to contribute and help keep it updated. Thanks man!
