### ISSUE TITLE
Steam Id doesn't seem to match Id in the profile url

### ISSUE THREAD

**Issue by nerdybeast** [jjbott/RocketLeagueReplayParser#53]
Hey I noticed something tonight parsing this replay: https://ballchasing.com/replay/c4bb45c2-07f0-4181-9129-41101bbcf730

It looks like these players Steam Id doesn't match the Id at the end of their profile url, example: 
![wundi](https://user-images.githubusercontent.com/15707802/223925565-f0ed903c-d7f5-4e45-ab8d-38cc4acb99a1.PNG)

It's not a big deal I just swear to myself that these values always seemed to match before. Is it possible the Steam Id is being parsed incorrectly? 

Perhaps not and the replay file does have a different value listed it's just weird because that Steam Id takes you to a completely different Steam user than the profile url. 

Anyway I just saw this and thought it was odd so I figured I mention it here in case you wanted to take a look.

Thanks man!

**Comment by tfausak** [comment]
The maximum safe integer in JSON is 9,007,199,254,740,991. This player's Steam ID (76,561,199,026,699,694) is bigger than that. I suspect it's being parsed correctly from the replay but mangled when generating the JSON. The only safe way to deal with these big numbers is to encode them as strings. See https://github.com/tfausak/rattletrap/issues/56 for this same issue with Rattletrap.

**Comment by nerdybeast** [comment]
@tfausak great catch, I suspected something like this was happening. You nailed it, the parsed results from @jjbott's library are working as expected but putting that data into the database (json) is mangling that value. I'll convert that value to a string before shoving in the database. Thanks for the response!
