### ISSUE TITLE
Unknown property TAGame.GameEvent_TA:MatchStartEpoch

### ISSUE THREAD

**Issue by Saqibul001** [jjbott/RocketLeagueReplayParser#56]
System.NotSupportedException: Unknown property TAGame.GameEvent_TA:MatchStartEpoch. Next bits in the data are 1011010101000010000110110110011000000000000000000000000000000000101011000110100000000000000000000000000110111000000000000000000000000111111100100000111010001010101010100000000000000000000000110100101000000000000000000000000000000101011100110100100000000000000000000000010100000000010101111001101010100000000000000000000000110101101100000000000000000000000000001010101011001010101000100100110000001100011011001011010010110010100001101110111010001100110011000000000011111110000100000000000000000000000000110000100010001010100010000011000100110010000010001011001010001010001100100011001010001001100010011011001000001010000010011000100010110011101100010000100110110001000010100111001001110000011100001000101100110010000010101000101000001011001100001000101100110000000000100000111100001000100000000000000000000000000000010110001001100110011000010110001101100100011001001110000000000101000100011010000100001000000000000000000000000000000110011000110100001100110011010100110110001100100011011101100101001101000011011001100001001100010110000011100100011001100011010000110111011001000011010101100100111000001110000100110011011000001110000101100001011000010011001100110100001101000011001100110000000000000000000110000000000000000000000000000010010100011001000100010100001100010111010000110110000101111011010000110110001100001011000000000110000001010001100110100001000010000000000000000000000000001100110010011000110110000100110000011001000011000011100001001100110011010100110011011001001110000101100001011001010011011001100100111000001110011000110100011000010011000001100011011000000110000011100001011001001110000100110001011000110011001000110111011000000000000000000010100000000000000000000000000000100011010000110011101100010111010000110101101100000111010000110011101000000000011000000101000101011010000100001000000000000000000000000001000011000101100010011001110110001100110100111000010011001101100011011000010110000001100010001100010110000101100110011000110011010000110111011000000110000001100100011000001110001000110110011000110011000001100110001101000110010001100100001101010110001000110000000000000000000010000000000000000000000000000101100101000011010000110100101100111011010100110011101000000000011000000101000111011010000100001000000000000000000000000000010011010000110000011000110011001101100000111000100110000001100011011001000110001000110111011000010110010011100001001100110110000011100010001100010110011001100010001101100011011001100000111001100011000001100110011001000110010101100001011000110011000011100000000000000000000110000000000000000000000000000110010101101011001001110100101100011011000110110101001100101111010110010100001100001111000000000110000001110001001000000000000000000000000000001010101011001010101000100000000011010011101000000000000000000000000000001001000000001010010110000001110101000000011000111110011000000000000000000111011010000100000000000000000001011010100001000000000000000000000010100000011000000000000000011100001110000100000000000000000000000001111110000000000000000000000001100000010000000000000000000000001111111001010111101100000000000000000000000000000110100000000101110001001010000101000100011000000000000000000000000000001001010001100100010001010000110001011101000011011000010111101101000011011000110000101100000000010000010101001000000000000000000000000000110101001101000010000100000000000000000000000000000011001100011010000110011001101010011011000110010001101110110010100110100001101100110000100110001011000001110010001100110001101000011011101100100001101010110010011100000111000010011001101100000111000010110000101100001001100110011010000110100001100110011000000000000000001100001001110001100000000000000000000000100110100100000000000000000000000000000010010111011001100110011001101011111110010110111011010000000000000000000000000010011111011000000000000000000000000000001101111001110000000000000000000100000000111010101000000000000000000000000011000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000001101010000000000000000000000011111111111101101011000011111111. Figure it out!

Im using your parser for a pet project. Could you help me out with this?

**Comment by tfausak** [comment]
This is probably related to patch 2.43, which was released yesterday: https://www.rocketleague.com/en/news/patch-notes-v2-43

Can you upload a replay file that fails to parse? You may have to compress it (with ZIP) to upload it here on GitHub.

**Comment by Saqibul001** [comment]
[717A7CB14FDA7F98E1F9C98D4C9C4E5B.zip](https://github.com/user-attachments/files/16874502/717A7CB14FDA7F98E1F9C98D4C9C4E5B.zip)

can you see this?

**Comment by tfausak** [comment]
Yup! And I get the same error with my parser:

```
ERROR: UnknownAttribute "TAGame.GameEvent_TA:MatchStartEpoch"

-- Context: Replay, content, Content, frames, element (0), Frame, replications, element (45), Replication, value, ReplicationValue, Updated, Attribute, value, AttributeValue
-- You are using Rattletrap version 13.0.3
```

https://github.com/tfausak/rattletrap/issues/307

**Comment by jjbott** [comment]
Thanks guys! I pushed version 3.8.0 just now!
