### ISSUE TITLE
Unable to parse replays after RL update

### ISSUE THREAD

**Issue by Saqibul** [jjbott/RocketLeagueReplayParser#57]
Im attaching a file that I cant seem to process after the latest RL update. Can you please look into it?

**Comment by Saqibul** [comment]
[B349D21546FCF69E4011F898A34787D0.zip](https://github.com/user-attachments/files/17488848/B349D21546FCF69E4011F898A34787D0.zip)

**Comment by Saqibul001** [comment]
Any luck? @jjbott

**Comment by jjbott** [comment]
Just a little! This guy is a bit complicated, with a new StructProperty and (I think?) new ByteProperty behavior. I'm about 62% sure how to fix them, but wont be able to try until after work. 

And, this is before the meat of the replay data, so I don't know if there are breaking changes in there yet.

**Comment by Saqibul001** [comment]
If you dont mind me asking, when do you get off work?

**Comment by jjbott** [comment]
Pushed version 3.9.0 to fix this 🤞
