### ISSUE TITLE
Question: Is it possible to find spectators from a replay file?

### ISSUE THREAD

**Issue by Saqibul001** [jjbott/RocketLeagueReplayParser#59]
I see the property "Engine.PlayerReplicationInfo:bIsSpectator". Can this be used to identify if the player is a spectator or not? If so, how would the output look like?

**Comment by jjbott** [comment]
I assume so, based on the property name, but I've never verified it. 

If you're digging through the JSON output there'd be a `"Engine.PlayerReplicationInfo:bIsSpectator": true,` in there.

If you're digging through the replay object, you can find the relevant actor states with something like 

```
 var spectatorActorStates = replay.Frames.Select(f => 
    f.ActorStates.Where(s => 
        s.Properties.Any(p => 
            p.Value.PropertyName == "Engine.PlayerReplicationInfo:bIsSpectator" 
            && (bool)(p.Value.Data)
        )
    )
).Where(p => p.Any());
```
